
stages:       
  - deploy


deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - build -f "BackMarvelVSCapman\BackMarvelVSCapman\Dockerfile" --force-rm -t backmarvelvscapman:latest "BackMarvelVSCapman" 
    - docker-compose up -d
  only:
    - develop
  tags:
    - vps
