
stages:       
  - deploy


deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - docker build -t backmarvelvscapman:latest ./BackMarvelVSCapman/BackMarvelVSCapman
    - docker-compose up -d
  only:
    - develop
  tags:
    - vps
