version: '3'
services:
  BackMarvelVSCapman:
    image: BackMarvelVSCapman:latest
    container_name: BackMarvelVSCapman
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.BackMarvelVSCapman.rule=Host(`BackMarvelVSCapman.douard.me`)"
      - "traefik.http.routers.BackMarvelVSCapman.service=BackMarvelVSCapman"
      - "traefik.http.services.BackMarvelVSCapman.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
